// EPIC (Extensible Position Independent Code)
//
// Source: github.com/Print3M/epic
// Author: Print3M
//
// Minimal stdarg.h for shellcoding (PIC-compatible)
// Generated by LLM: Claude 4.5 (reasoning)

#pragma once

/* Variable argument list type */
typedef __builtin_va_list va_list;

/* Initialize variable argument list */
#define va_start(ap, last) __builtin_va_start(ap, last)

/* Retrieve next argument from list */
#define va_arg(ap, type) __builtin_va_arg(ap, type)

/* End variable argument list processing */
#define va_end(ap) __builtin_va_end(ap)

/* Copy variable argument list (C99+) */
#define va_copy(dest, src) __builtin_va_copy(dest, src)
