// EPIC (Extensible Position Independent Code)
//
// Source: github.com/Print3M/epic
// Author: Print3M
//
// This is an example module generated by EPIC.
//
#pragma once
#include <epic.h>

namespace hello {

MODULE void calc();

MODULE void message(const char *msg);

}