// EPIC (Extensible Position Independent Code)
//
// Source: github.com/Print3M/epic
// Author: Print3M
//
// This is an example module generated by EPIC.
//
#pragma once
#include <epic.h>

namespace utils {
	MODULE void message(const char* msg, const char* title);
    MODULE void message_hex(void* p, const char* title);
	MODULE void message_encode(const char* msg, int len, const char* title);
	MODULE int get_pid_by_name(const wchar_t* target);
	MODULE HANDLE open_process_by_pid(int pid);
	MODULE bool proc_mini_dump(HANDLE h, DWORD pid);
}