// EPIC (Extensible Position Independent Code)
//
// Source: github.com/Print3M/epic
// Author: Print3M
//
// This is an example module generated by EPIC.
//
#pragma once
#include <epic.h>

namespace utils {
	MODULE HANDLE open_process_by_pid(int pid);
	MODULE HANDLE open_process_by_name(const char* msg);
	MODULE BOOL read_memory(HANDLE h, uint64_t addr, void* buf, SIZE_T size);
	MODULE void message(const char *msg);
}