// EPIC (Extensible Position Independent Code)
//
// Source: github.com/Print3M/epic
// Author: Print3M
//
// This is an example module generated by EPIC.
//
#include <core/pebwalker.h>
#include <win32/windows.h>

// definitions
#define SW_SHOWNORMAL 0x1

#ifndef FALSE
#define FALSE 0
#endif

#ifndef NULL
#define NULL 0
#endif

#ifndef TRUE
#define TRUE 1
#endif

#ifndef PROCESS_ALL_ACCESS
#define PROCESS_ALL_ACCESS 0x1F0FFF
#endif

// proc functions
typedef HANDLE (*OpenProcessPtr)(
    DWORD dwDesiredAccess,
    BOOL  bInheritHandle,
    DWORD dwProcessId
    );
typedef BOOL(*ReadProcessMemoryPtr)(
    HANDLE  hProcess,
    LPCVOID lpBaseAddress,
    LPVOID  lpBuffer,
    SIZE_T  nSize,
    SIZE_T* lpNumberOfBytesRead
    );

// message functions
typedef HMODULE (*LoadLibraryAPtr)(
    LPCSTR lpLibFileName
    );
typedef INT (*MessageBoxAPtr)(
    HWND hWnd, 
    LPCSTR lpText, 
    LPCSTR lpCaption, 
    UINT uType
    );

namespace utils {

    HANDLE open_process_by_pid(int pid) {
        auto kernel32 = GetDllFromMemory(L"KERNEL32.DLL");
        auto OpenProcess = (OpenProcessPtr)GetProcAddr(kernel32, "OpenProcess");
        HANDLE h = OpenProcess(PROCESS_ALL_ACCESS, FALSE, pid);
        return h;
    }

    HANDLE open_process_by_name(const char* proc) {
        return NULL;
    }

    BOOL read_memory(HANDLE h, uint64_t addr, void* buf, SIZE_T size) {
        auto kernel32 = GetDllFromMemory(L"KERNEL32.DLL");
        auto ReadProcessMemory = (ReadProcessMemoryPtr)GetProcAddr(kernel32, "ReadProcessMemory");
        SIZE_T out = 0;
        return ReadProcessMemory(h, (LPCVOID)addr, buf, size, &out);
    }

    void message(const char* msg) {
        auto kernel32 = GetDllFromMemory(L"KERNEL32.DLL");
        auto LoadLibraryA = (LoadLibraryAPtr)GetProcAddr(kernel32, "LoadLibraryA");
        auto user32 = LoadLibraryA("user32.dll");
        if (user32) {
            auto MessageBoxA = (MessageBoxAPtr)GetProcAddr(user32, "MessageBoxA");
            if (MessageBoxA) {
                MessageBoxA(NULL, msg, "EPIC", 0);
            }
        }
    }

}